// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use diesel::Queryable;
use serde::Serialize;
use chrono::NaiveDate;
use diesel::Insertable;

#[derive(Queryable, Debug, Serialize)]
pub struct Article {
    pub id: i32,
    pub title: String,
    pub content: String,
    pub created_by: i32,
    #[serde(skip_serializing)]
    pub created_on: Option<NaiveDate>,
}

#[derive(Queryable, Debug, Serialize)]
pub struct User {
    pub id: i32,
    pub first_name: String,
    pub last_name: String,
}

use crate::schema::users;

#[derive(Insertable)]
#[diesel(table_name = users)]
pub struct NewUser<'a> {
    pub first_name: &'a str,
    pub last_name: &'a str,
}